//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FESA.SCM.UserLoadJob.ConsultaUsuarios {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsADItem", Namespace="http://schemas.datacontract.org/2004/07/WsConsultaADWCF")]
    [System.SerializableAttribute()]
    public partial class clsADItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CentroCostoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodEmpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoCompaniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoEmpleadoJefeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoGerenciaDivisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPuestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoUbicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoUnidadFuncionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoJefeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionCentroCostoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionGerenciaDivisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionPuestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionUnidadFuncionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCompaniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreGerenteDivisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreJefeInmediatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumDocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RPMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TOfiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoTrabajadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UbicacionFisicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userPasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Anexo {
            get {
                return this.AnexoField;
            }
            set {
                if ((object.ReferenceEquals(this.AnexoField, value) != true)) {
                    this.AnexoField = value;
                    this.RaisePropertyChanged("Anexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cell {
            get {
                return this.CellField;
            }
            set {
                if ((object.ReferenceEquals(this.CellField, value) != true)) {
                    this.CellField = value;
                    this.RaisePropertyChanged("Cell");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CentroCosto {
            get {
                return this.CentroCostoField;
            }
            set {
                if ((object.ReferenceEquals(this.CentroCostoField, value) != true)) {
                    this.CentroCostoField = value;
                    this.RaisePropertyChanged("CentroCosto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodEmp {
            get {
                return this.CodEmpField;
            }
            set {
                if ((object.ReferenceEquals(this.CodEmpField, value) != true)) {
                    this.CodEmpField = value;
                    this.RaisePropertyChanged("CodEmp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoCompania {
            get {
                return this.CodigoCompaniaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoCompaniaField, value) != true)) {
                    this.CodigoCompaniaField = value;
                    this.RaisePropertyChanged("CodigoCompania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoEmpleado {
            get {
                return this.CodigoEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoEmpleadoField, value) != true)) {
                    this.CodigoEmpleadoField = value;
                    this.RaisePropertyChanged("CodigoEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoEmpleadoJefe {
            get {
                return this.CodigoEmpleadoJefeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoEmpleadoJefeField, value) != true)) {
                    this.CodigoEmpleadoJefeField = value;
                    this.RaisePropertyChanged("CodigoEmpleadoJefe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoGerenciaDivision {
            get {
                return this.CodigoGerenciaDivisionField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoGerenciaDivisionField, value) != true)) {
                    this.CodigoGerenciaDivisionField = value;
                    this.RaisePropertyChanged("CodigoGerenciaDivision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPuesto {
            get {
                return this.CodigoPuestoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPuestoField, value) != true)) {
                    this.CodigoPuestoField = value;
                    this.RaisePropertyChanged("CodigoPuesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoUbicacion {
            get {
                return this.CodigoUbicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoUbicacionField, value) != true)) {
                    this.CodigoUbicacionField = value;
                    this.RaisePropertyChanged("CodigoUbicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoUnidadFuncional {
            get {
                return this.CodigoUnidadFuncionalField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoUnidadFuncionalField, value) != true)) {
                    this.CodigoUnidadFuncionalField = value;
                    this.RaisePropertyChanged("CodigoUnidadFuncional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoJefe {
            get {
                return this.CorreoJefeField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoJefeField, value) != true)) {
                    this.CorreoJefeField = value;
                    this.RaisePropertyChanged("CorreoJefe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionCentroCosto {
            get {
                return this.DescripcionCentroCostoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionCentroCostoField, value) != true)) {
                    this.DescripcionCentroCostoField = value;
                    this.RaisePropertyChanged("DescripcionCentroCosto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionGerenciaDivision {
            get {
                return this.DescripcionGerenciaDivisionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionGerenciaDivisionField, value) != true)) {
                    this.DescripcionGerenciaDivisionField = value;
                    this.RaisePropertyChanged("DescripcionGerenciaDivision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionPuesto {
            get {
                return this.DescripcionPuestoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionPuestoField, value) != true)) {
                    this.DescripcionPuestoField = value;
                    this.RaisePropertyChanged("DescripcionPuesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionUnidadFuncional {
            get {
                return this.DescripcionUnidadFuncionalField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionUnidadFuncionalField, value) != true)) {
                    this.DescripcionUnidadFuncionalField = value;
                    this.RaisePropertyChanged("DescripcionUnidadFuncional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError {
            get {
                return this.MensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorField, value) != true)) {
                    this.MensajeErrorField = value;
                    this.RaisePropertyChanged("MensajeError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCompania {
            get {
                return this.NombreCompaniaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCompaniaField, value) != true)) {
                    this.NombreCompaniaField = value;
                    this.RaisePropertyChanged("NombreCompania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreGerenteDivision {
            get {
                return this.NombreGerenteDivisionField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreGerenteDivisionField, value) != true)) {
                    this.NombreGerenteDivisionField = value;
                    this.RaisePropertyChanged("NombreGerenteDivision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreJefeInmediato {
            get {
                return this.NombreJefeInmediatoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreJefeInmediatoField, value) != true)) {
                    this.NombreJefeInmediatoField = value;
                    this.RaisePropertyChanged("NombreJefeInmediato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumDoc {
            get {
                return this.NumDocField;
            }
            set {
                if ((object.ReferenceEquals(this.NumDocField, value) != true)) {
                    this.NumDocField = value;
                    this.RaisePropertyChanged("NumDoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RPM {
            get {
                return this.RPMField;
            }
            set {
                if ((object.ReferenceEquals(this.RPMField, value) != true)) {
                    this.RPMField = value;
                    this.RaisePropertyChanged("RPM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TOfi {
            get {
                return this.TOfiField;
            }
            set {
                if ((object.ReferenceEquals(this.TOfiField, value) != true)) {
                    this.TOfiField = value;
                    this.RaisePropertyChanged("TOfi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoTrabajador {
            get {
                return this.TipoTrabajadorField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoTrabajadorField, value) != true)) {
                    this.TipoTrabajadorField = value;
                    this.RaisePropertyChanged("TipoTrabajador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UbicacionFisica {
            get {
                return this.UbicacionFisicaField;
            }
            set {
                if ((object.ReferenceEquals(this.UbicacionFisicaField, value) != true)) {
                    this.UbicacionFisicaField = value;
                    this.RaisePropertyChanged("UbicacionFisica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userPassword {
            get {
                return this.userPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.userPasswordField, value) != true)) {
                    this.userPasswordField = value;
                    this.RaisePropertyChanged("userPassword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConsultaUsuarios.IConsultaAD")]
    public interface IConsultaAD {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaAD/Buscar", ReplyAction="http://tempuri.org/IConsultaAD/BuscarResponse")]
        FESA.SCM.UserLoadJob.ConsultaUsuarios.clsADItem[] Buscar(string pi_strApellido, string pi_strCodigo, string pi_strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaAD/Buscar", ReplyAction="http://tempuri.org/IConsultaAD/BuscarResponse")]
        System.Threading.Tasks.Task<FESA.SCM.UserLoadJob.ConsultaUsuarios.clsADItem[]> BuscarAsync(string pi_strApellido, string pi_strCodigo, string pi_strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaAD/ListarTodos", ReplyAction="http://tempuri.org/IConsultaAD/ListarTodosResponse")]
        FESA.SCM.UserLoadJob.ConsultaUsuarios.clsADItem[] ListarTodos(string pi_strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultaAD/ListarTodos", ReplyAction="http://tempuri.org/IConsultaAD/ListarTodosResponse")]
        System.Threading.Tasks.Task<FESA.SCM.UserLoadJob.ConsultaUsuarios.clsADItem[]> ListarTodosAsync(string pi_strPassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConsultaADChannel : FESA.SCM.UserLoadJob.ConsultaUsuarios.IConsultaAD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaADClient : System.ServiceModel.ClientBase<FESA.SCM.UserLoadJob.ConsultaUsuarios.IConsultaAD>, FESA.SCM.UserLoadJob.ConsultaUsuarios.IConsultaAD {
        
        public ConsultaADClient() {
        }
        
        public ConsultaADClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultaADClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaADClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaADClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FESA.SCM.UserLoadJob.ConsultaUsuarios.clsADItem[] Buscar(string pi_strApellido, string pi_strCodigo, string pi_strPassword) {
            return base.Channel.Buscar(pi_strApellido, pi_strCodigo, pi_strPassword);
        }
        
        public System.Threading.Tasks.Task<FESA.SCM.UserLoadJob.ConsultaUsuarios.clsADItem[]> BuscarAsync(string pi_strApellido, string pi_strCodigo, string pi_strPassword) {
            return base.Channel.BuscarAsync(pi_strApellido, pi_strCodigo, pi_strPassword);
        }
        
        public FESA.SCM.UserLoadJob.ConsultaUsuarios.clsADItem[] ListarTodos(string pi_strPassword) {
            return base.Channel.ListarTodos(pi_strPassword);
        }
        
        public System.Threading.Tasks.Task<FESA.SCM.UserLoadJob.ConsultaUsuarios.clsADItem[]> ListarTodosAsync(string pi_strPassword) {
            return base.Channel.ListarTodosAsync(pi_strPassword);
        }
    }
}
