//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FESA.SCM.FieldService.BL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Template {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Template() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FESA.SCM.FieldService.BL.Resources.Template", typeof(Template).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; lang=&quot;en&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///		&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;ie=edge&quot;&gt;
        ///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///		&lt;title&gt;&lt;/title&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///
        ///			html {
        ///			min-height: 100%;
        ///			position: relative;
        ///			}
        ///
        ///			body {
        ///			margin: 0;
        ///			padding: 0;
        ///			font-family: Arial;
        ///			margin-bottom: 40px;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActString {
            get {
                return ResourceManager.GetString("ActString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; lang=&quot;en&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///		&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;ie=edge&quot;&gt;
        ///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///		&lt;title&gt;&lt;/title&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///
        ///			html {
        ///			min-height: 100%;
        ///			position: relative;
        ///			}
        ///
        ///			body {
        ///			margin: 0;
        ///			padding: 0;
        ///			font-family: Arial;
        ///			margin-bottom: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExeString {
            get {
                return ResourceManager.GetString("ExeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; lang=&quot;en&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///		&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;ie=edge&quot;&gt;
        ///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///		&lt;title&gt;&lt;/title&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			body {
        ///			margin: 0;
        ///			padding: 0;
        ///			min-width: 100% !important;
        ///			letter-spacing: 0.7px;
        ///			}
        ///
        ///			img {
        ///			height: auto;
        ///			}
        ///
        ///			.c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///		&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;ie=edge&quot;&gt;
        ///		&lt;title&gt;&lt;/title&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			body {
        ///			margin: 0;
        ///			padding: 0;
        ///			min-width: 100% !important;
        ///			letter-spacing: 0.5px;
        ///			font-family: serif;
        ///			}
        ///
        ///			.content {
        ///			width: 100%;
        ///			max-width: 600px;
        ///			}
        ///
        ///			.header {
        ///			background-image: url(https://serviciodecampo.blob.core.windows [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ServiceClient {
            get {
                return ResourceManager.GetString("ServiceClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///		&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;ie=edge&quot;&gt;
        ///		&lt;title&gt;&lt;/title&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			body {
        ///			margin: 0;
        ///			padding: 0;
        ///			min-width: 100% !important;
        ///			letter-spacing: 0.5px;
        ///			font-family: serif;
        ///			}
        ///
        ///			.content {
        ///			width: 100%;
        ///			max-width: 600px;
        ///			}
        ///
        ///			.header {
        ///			background-image: url(https://serviciodecampo.blob.core.windows [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ServiceFull {
            get {
                return ResourceManager.GetString("ServiceFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///		&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;ie=edge&quot;&gt;
        ///		&lt;title&gt;&lt;/title&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			body {
        ///			margin: 0;
        ///			padding: 0;
        ///			min-width: 100% !important;
        ///			letter-spacing: 0.5px;
        ///			font-family: serif;
        ///			}
        ///
        ///			.content {
        ///			width: 100%;
        ///			max-width: 600px;
        ///			}
        ///
        ///			.header {
        ///            background-image: url(https://serviciodecampo.blob.cor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ServiceGeneral {
            get {
                return ResourceManager.GetString("ServiceGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///		&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;ie=edge&quot;&gt;
        ///		&lt;title&gt;&lt;/title&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			body {
        ///			margin: 0;
        ///			padding: 0;
        ///			min-width: 100% !important;
        ///			letter-spacing: 0.5px;
        ///			font-family: serif;
        ///			}
        ///
        ///			.content {
        ///			width: 100%;
        ///			max-width: 600px;
        ///			}
        ///
        ///			.header {
        ///			background-image: url(https://serviciodecampo.blob.core.windows [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ServiceOffline {
            get {
                return ResourceManager.GetString("ServiceOffline", resourceCulture);
            }
        }
    }
}
