#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FESA.SCM.Android.Resource", IsApplication=true)]

namespace FESA.SCM.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLCrypto.Resource.String.ApplicationName = global::FESA.SCM.Android.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::FESA.SCM.Android.Resource.String.Hello;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::FESA.SCM.Android.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::FESA.SCM.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int assignmentactiveblue = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_atras = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_check = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_close = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_enviando = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btn_gracias = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_mas = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_settings = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_user = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_ver_contra = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int datos_servicio = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int documentos = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int fondoInicio = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int fondoPrincipal = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int green = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Icon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int icon_user = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int logo = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int logoapp = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int menu = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int red = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int titulo = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int yellow = 2130837526;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int appName = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int login = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int logo = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int userName = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int userPassword = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
